# Generated by Django 3.2.8 on 2021-10-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarista',
            name='complemnto',
        ),
        migrations.AddField(
            model_name='diarista',
            name='complemento',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='diarista',
            name='cep',
            field=models.CharField(max_length=8),
        ),
    ]
