# Generated by Django 3.2.8 on 2021-10-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_diarista_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarista',
            name='cep',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='diarista',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
    ]
