# Generated by Django 3.2.8 on 2021-10-14 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_diarista_cidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diarista',
            old_name='cidade',
            new_name='Cidade',
        ),
    ]
