# Generated by Django 3.2.8 on 2021-10-14 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_cidade_diarista_cidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diarista',
            old_name='Cidade',
            new_name='cidade',
        ),
    ]
